apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: redditeye
spec:
  secretName: redditeye
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: redditeye.com
  dnsNames:
  - redditeye.com
  acme:
    config:
    - dns01:
        provider: route53
        ingressClass: nginx
      domains:
      - redditeye.com