apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redditeye
  labels:
    app: redditeye
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redditeye
    spec:
      containers:
        - name: redditeye
          image: kristianwindsor/redditeye.com
          ports:
            - containerPort: 80
