version: "3.7"
services:
  webui:
    build:
      context: .
      dockerfile: webui.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./webui/:/usr/local/apache2/htdocs/
    restart: always
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/usr/src/app/
    restart: always