version: "3.7"
services:
  webui:
    build: webui
    ports:
      - 80:80
    volumes:
      - ./webui/src/:/usr/local/apache2/htdocs/
    restart: always
  backend:
    build: backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/
    restart: always