apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redditeye
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
spec:
  rules:
  - host: redditeye.com
    http:
      paths:
      - path: /
        backend:
          serviceName: redditeye
          servicePort: 80
  - host: backend.redditeye.com
    http:
      paths:
      - path: /
        backend:
          serviceName: redditeye
          servicePort: 5000
  tls:
  - secretName: redditeye
    hosts:
    - redditeye.com
    - '*.redditeye.com'